### ISSUE TITLE
Usability for Filler files: Put transaction data in the expect: section

### ISSUE THREAD

**Issue by qbzzt** [ethereum/retesteth#113]
When we have a number of data values in GeneralStateTests, we specify them in the **transaction:** field:

```
  transaction:
    data:
    # Type:    01 - RETURN    02 - REVERT
    # Gas

    # Enough gas for the called contract to finish
    - :abi f(uint,uint) 1 0x36
    - :abi f(uint,uint) 2 0x36
     .
     .
     .
```

Then, we refer to them by number in the **expect:** section:
```
  expect:

    # Calls that don't return data
    - indexes:
        data:
        - !!int 2
        - !!int 3
        - !!int 4
```

This means we need to go back and forth between these two sections to figure out what is happening. It also makes it difficult
to organize the data values according to a rational scheme, because when we reorder them we need to change all the references in the **expect:** sections. 

It would be a lot easier to write tests if we could put the values directly in the **expect:** section:
```
  expect:

    # Calls that don't return data
    - indexes:
        data:
        - :abi f(uint,uint) 1 0x36
        - :abi f(uint,uint) 1 0x36
```

And have `retesteth --filltests` worry about putting them in the transaction and numbering them corrrectly. We might end up with more values (if we use the data field with different **expect:** sections, for example with different gas or network), but the extra storage won't be a problem.

On a related note, when a test fails we see the sequence number of the data entry. It would be nice if we could in addition / instead see the value.
